### ISSUE TITLE
Paths are not translated properly from python package names

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#198]
### What happened?

When creating a new library project with name `client-base`, I changed the `python_package` variable from the default `frequenz.client_common` to `frequenz.client.common`, but files were still created as `src/frequenz/client_common`.

### What did you expect instead?

I expected the directories to look like `src/frequenz/client/common` and all top-level files to be placed in there.

### Affected part(s)

Cookiecutter template (part:cookiecutter)

### Extra information

FYI @shsms, please confirm if this is the issue you observed.

**Comment by shsms** [comment]
Yup, that was it, although I typed the module name as `client.common`, in cookiecutter.
