### ISSUE TITLE
Add tests for Python 3.12 and update readme

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-repo-config-python#269]
### What's needed?

This is already working with 3.12, as we've seen in the SDK, just need to decide whether to add tests, and mention in the readme.

**Comment by llucax** [comment]
Isn't it this a dupe for #168 ?

**Comment by shsms** [comment]
Oops, yes.

**Comment by shsms** [comment]
And I forgot that it is not as simple, because we only have hacks to get the SDK to work.
