### ISSUE TITLE
Add git submodules dependency checks

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#43]
`api` projects use Git submodules to manage dependencies for protobuf files.

We use *dependabot* to keep dependencies up to date and while dependabot does support git submdules as a dependency management system, it support is pretty basic, and submodules are always updated to the lastest default head and there is no way to configure it to update at least to tags, much less to configure updates following semver.

* https://github.com/dependabot/dependabot-core/issues/1639

The current alternative (as some people did in that issue) is to implement our own workflow to check this (or send a PR to dependabot to improve support).

The most basic approach would be to schedule a workflow to run periodically that could just be looking for new tags in submodules (possibly following semver) and just failing the job if there are updates, so at least we get notified when something need updating.  The update process would still be manual.

Please note that this is only needed (for now) for the google common proto files, as for internal dependencies we'll still get notified about new releases by the Python ecosystem via dependabot.

**Comment by llucax** [comment]
Done by #44.
