### ISSUE TITLE
`-` sign in `name` should be replaced with `_` for `src/` module/folder creation

### ISSUE THREAD

**Issue by Marenz** [frequenz-floss/frequenz-repo-config-python#79]
### What happened?

given the name `fcr-balancing`, the folder `src/frequenz/actor/fcr-balancing` was created, 

### What did you expect instead?

but I believe we want to use `_` here, at least my existing folder was `fcr_balancing` (migrating project).

### Affected part(s)

Affects only the configuration of actor repos (part:actor-only)

### Extra information

If this works as intended, feel free to close.

**Comment by llucax** [comment]
We said it would be probably better to replace `-` with `.` instead, to build a nested namespace. So in the example cited about, if the name is `fcr-balancing`, then the directory structure should be `src/frequenz/actor/fcr/balancing` and the python package `frequenz.actor.fcr.balancing`.

The path part might be a bit more complicated to implement though, as the files are generated by cookiecutter, so we should move the generated files in the post hook. Is something we are already doing for `api` projects, so it is not impossible either.

**Comment by llucax** [comment]
I looked into this and accepting `.` to change the directory structure is way too complicated to justify it, so I implemented the original idea. Now if `fcr-balancing` is used as `name`, then the `python_package` should be `frequenz.actor.fcr_balancing` and the directory `src/frequenz/actor/fcr_balancing` should be created.

**Comment by Marenz** [comment]
> I looked into this and accepting . to change the directory structure is way too complicated to justify it, 

Aw, really? It sounded so structured and easy

**Comment by llucax** [comment]
Yeah, because the file structure is "hardcoded" in the templates, so in the post script we need to search for dots and start moving entire tree around, and remove the old ones. Of course it is doable, but not something I'm willing to spend so much time on right now :-/
