### ISSUE TITLE
Add RELEASE_NOTES template

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-repo-config-python#9]
SDK example: https://github.com/frequenz-floss/frequenz-sdk-python/blob/v0.x.x/.github/RELEASE_NOTES.template.md

Probably we should also find a way to share this RELEASE_NOTES template to the projects using this library, so we have it only in one place. Worst case scenario it can be provided in the Python package and add a binary that will just reset the release notes using this template.

**Comment by llucax** [comment]
There was some push back about this from @stefan-brus-frequenz and @tiyash-basu-frequenz , mentioning it was just too much work for small projects (like APIs), where it is usually enough to just use the automatically generated changelog by GitHub (which just lists all the PRs in the release).

Maybe we should discuss this, alternatives, etc. in a discussion before adding this to the repo-config.

**Comment by llucax** [comment]
Blocked on: https://github.com/frequenz-floss/frequenz-repo-config-python/discussions/52

**Comment by llucax** [comment]
Unblocking because now this file is mentioned in the Contributing Guide. We can change it in the future after the road in #52 is clear.
